#!/usr/bin/env python3
# Author: Sourav Chandra
# Analyzer JSON → Structured, Severity-first Markdown Report

import json
from pathlib import Path
from typing import Dict, List, Any
from collections import defaultdict

SEVERITY_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]

def normalize_severity(value: str) -> str:
    if not value:
        return "INFO"
    v = value.upper()
    for s in SEVERITY_ORDER:
        if s in v:
            return s
    return "INFO"

def extract_severities(obj: Any, bucket: Dict[str, int]):
    if isinstance(obj, dict):
        for k, v in obj.items():

            key = k.lower()

            if key in (
                "severity", "risklevel", "risk_level",
                "priority", "impact"
            ):
                bucket[normalize_severity(str(v))] += 1

            # CVSS numeric mapping
            if key in ("cvss", "cvss_score"):
                try:
                    score = float(v)
                    if score >= 9:
                        bucket["CRITICAL"] += 1
                    elif score >= 7:
                        bucket["HIGH"] += 1
                    elif score >= 4:
                        bucket["MEDIUM"] += 1
                    elif score > 0:
                        bucket["LOW"] += 1
                except Exception:
                    pass

            extract_severities(v, bucket)

    elif isinstance(obj, list):
        for i in obj:
            extract_severities(i, bucket)

def convert(json_path: Path, md_path: Path) -> None:
    with json_path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    md: List[str] = []

    md.extend([
        "# 🔍 AI & GenOps – Analyzer Report",
        "",
        "**Generated by:** AI & GenOps Guardian",
        f"**Source:** `{json_path.name}`",
        "",
        "---",
        ""
    ])

    # -------- FIXED SEVERITY SCAN --------
    severity_counts = defaultdict(int)

    for tool, result in data.items():
        if not isinstance(result, dict):
            continue

        # Parse JSON buried inside stdout
        stdout = result.get("stdout", "")
        try:
            parsed = json.loads(stdout)
            extract_severities(parsed, severity_counts)
        except Exception:
            pass

        extract_severities(result, severity_counts)

    md.extend([
        "## 🚦 Severity Overview",
        "",
        "| Severity | Count |",
        "|----------|-------|"
    ])

    for sev in SEVERITY_ORDER:
        md.append(f"| {sev} | {severity_counts.get(sev, 0)} |")

    md.extend(["", "---", ""])

    # ---------- Tool Summary ----------
    md.extend([
        "## 🧰 Tool Execution Summary",
        "",
        "| Tool | Status |",
        "|-----|--------|"
    ])

    for tool, result in data.items():
        rc = result.get("returncode", 0) if isinstance(result, dict) else "N/A"
        status = "✅ Clean" if rc == 0 else "❌ Findings"
        md.append(f"| {tool} | {status} |")

    md.extend(["", "---", ""])

    md.append("## 📋 Detailed Tool Results\n")

    for tool, tool_data in data.items():
        md.extend([f"## 🔧 {tool}", "```json", json.dumps(tool_data, indent=2), "```", "\n---\n"])

    md_path.write_text("\n".join(md), encoding="utf-8")

if __name__ == "__main__":
    import sys
    convert(Path(sys.argv[1]), Path(sys.argv[2]))
