# Author: Sourav Chandra
# JSON → Document-style Markdown converter

import json
from pathlib import Path
from typing import Any


MAX_TEXT_LEN = 800


def truncate(text: str, limit: int = MAX_TEXT_LEN) -> str:
    if len(text) > limit:
        return text[:limit] + "\n…(truncated)"
    return text


def render_tool(tool: str, data: dict) -> list[str]:
    lines = []
    returncode = data.get("returncode", 0)

    status = "✅ Clean" if returncode == 0 else "❌ Issues detected"
    lines.append(f"## 🔧 {tool.capitalize()}")
    lines.append(f"**Status:** {status}\n")

    stdout = data.get("stdout", "").strip()
    stderr = data.get("stderr", "").strip()

    if stdout:
        lines.append("### 📄 Findings / Output")
        lines.append("```text")
        lines.append(truncate(stdout))
        lines.append("```")

    if stderr:
        lines.append("\n### ⚠ Errors / Warnings")
        lines.append("```text")
        lines.append(truncate(stderr))
        lines.append("```")

    lines.append("\n---\n")
    return lines


def convert(json_path: Path, md_path: Path) -> None:
    with json_path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    md: list[str] = []

    # ---------- Header ----------
    md.extend([
        "# 🔍 Repository Analyzer Report",
        "",
        "**Generated by:** AI & GenOps Guardian",
        f"**Source JSON:** `{json_path.name}`",
        "",
        "---",
        ""
    ])

    # ---------- Executive Summary ----------
    total_tools = len(data)
    failed_tools = sum(
        1 for v in data.values()
        if isinstance(v, dict) and v.get("returncode", 0) != 0
    )

    md.extend([
        "## 📌 Executive Summary",
        f"- Tools executed: **{total_tools}**",
        f"- Tools with findings: **{failed_tools}**",
        "",
        "---",
        ""
    ])

    # ---------- Tool-wise Sections ----------
    for tool, tool_data in data.items():
        if isinstance(tool_data, dict):
            md.extend(render_tool(tool, tool_data))
        else:
            md.append(f"## 🔧 {tool}")
            md.append("```text")
            md.append(truncate(str(tool_data)))
            md.append("```")
            md.append("\n---\n")

    md_path.write_text("\n".join(md), encoding="utf-8")


# CLI support
if __name__ == "__main__":
    import sys

    if len(sys.argv) != 3:
        print("Usage: json_to_md.py <input.json> <output.md>")
        sys.exit(1)

    convert(Path(sys.argv[1]), Path(sys.argv[2]))
    print("✔ Markdown report generated")
